re-rxjs/react-rxjs

src/useObservable.ts, test/connectFactoryObservable.test.tsx
Recently I've been thinking about a possible issue with the current re-rxjs bindings.
It has to do with possible false assumptions when using `connectFactoryObservable`. As an example, imagine we write a factory observable such as:
```ts
const [useUserPosts] = connectFactoryObservable(
(userId: string) => user$.pipe(
map(users => users[id]),
map(user => user.posts),
combineLatest(post$),
map(([ids, posts]) => ids.map(id => posts[id]))
)
```
We might make the assumption that, as we will call `useUserPosts()` in components that receive an existing `userId`, we don't need to check whether that userId exists (again, because we're going to call this hook with existing ids).
The problem comes when a user is removed. In this logic, no error should be thrown because as the component gets …
=> prevent surfacing errors happening in components to be unmounted

src/connectFactoryObservable.ts, src/useObservable.ts
I forgot to get rid of it when we decided to stop exposing `useObservable`
=> useObservable: remove unnecessary argument

package.json, src/index.tsx, src/operators/distinct-share-replay.ts, src/utils/batch.ts, src/utils/react-batched-updates.native.ts, src/utils/react-batched-updates.ts
I've been thinking a lot about this lately and I'm almost convinced that it doesn't make sense for us to use the `unstable_batchedUpdates`... The reason being that those changes that come from within react event-handlers (e.g. `onClick`) will be batched already. On the other hand, those updates that come from external sources (i.e: APIs whether they are socket-based or REST) the recommendation would be to observer them through the `asapScheduler`. In other words, it would be up to the user to decide the priority of each "event", but if this library is used as it's intended, then observing changes through the `asapScheduler` should remove the need for prematurely batching external updates.
Anyways, this is a decision that can be revisited in the future and it would only imply a patch …
=> Remove React-(dom/native) unstable_batchedUpdates

src/createInput.ts, test/createInput.test.ts
I've been thinking about this as I was writing the docs and I've realized that `createInput` should also allow for "void" inputs... So, I think that this is the behavior that I would like to have on `createInput`. @voliva thoughts?
=> Improve createInput types and behavior

src/index.tsx, test/operators/distinct-share-replay.test.ts, test/operators/react-enhancer.test.ts, test/useObservable.test.tsx
As I was writing the docs I realized that the `distinctShareReplay` that we are currently exposing is leaking some internals that I rather not to leak:
- The `teardown` function is not a normal `finalize` because it only runs when the `refCount` goes down to zero, and it's meant for internal usage only. So, I rather not to expose that.
- The `BehaviorObservable` it's an internal type, there is no need for the consumers of this library to know about its existence.
=> Improve distinctShareReplay

src/operators/distinct-share-replay.ts, test/connectFactoryObservable.test.tsx, test/operators/distinct-share-replay.test.ts
This addresses one of the issues found by @voliva on #20 (Thanks a lot for pointing that out BTW!)
Is this living proof that marble-tests can't be pretty useless for some stuff? Why can't I find a way to add a marble test that ensures this behavior?
=> Fix: distinctShareReplay shouldn't skip values on sync subscriptions

README.md
Forgive me I was late on reviewing the initial docs PR - Here are my suggestions that I think it improves them a bit.
I understand that those were initial docs, to have something better than a placeholder, so I agree that maybe this PR should be closed instead and this will be addressed when working on the final docs. But in case they might help, here they are.
Addresses two main points:
1. I didn't fully like adding keywords that people might not be familiar with. Specifically `shared` and `replayable`. So I rephrased that.
2. Some of the operators had the actual implementation in them. Although I can see how this is useful to get the point across (e.g. `distinctShareReplay`), I felt like in some places it was redundant (if people want to see the how it's implemented it's just 2 clicks …
=> docs: add usage examples to every method

test/connectObservable.test.tsx, test/operators/suspend.test.ts, test/operators/suspended.test.ts, test/operators/switchMapSuspended.test.ts
This PR covers the rest of test improvements identified in #20 
For the "it works in suspense" what I did is in `connectObservable` cover the part where it integrates with react (by using exclusively SUSPENSE), and then all the "sugar operators" are tested in isolation.
IMPORTANT -> I made a change to `switchMapSuspended` which I think it makes it a bit smarter. I ran into that when thinking on tests for that operator.
As it's currently in main branch, if a new update comes from the source stream before the inner stream has published anything, that inner stream will get cancelled, a new SUSPENSE will be emitted and a new subscription to the inner stream will be made.
I think it would make sense for `switchMapSuspended` for only emitting one single SUSPENSE while there are no new data. I …
=> test: updates on connectObservable, suspense

src/internal/BehaviorObservable.ts, src/internal/react-enhancer.ts, src/internal/share-latest.ts, src/internal/useObservable.ts, test/connectFactoryObservable.test.tsx, test/connectObservable.test.tsx
This was fun! :sweat_smile:
This PR finishes the work that @voliva started on #53 
Thanks a lot @voliva for reporting this issue and for all the details that you've provided in #53, we should go over all this stuff at some point.
=> fix(error-handling): fix error-handling issues with suspense

README.md, packages/core/README.md, packages/dom/README.md, packages/dom/src/batchUpdates.ts, packages/utils/README.md, packages/utils/src/groupInMap.ts, packages/utils/src/mergeWithKey.ts
Having the API in these READMEs is something temporary while we finish the react-rxjs.org docs site. Once that's done these readmes will just redirect the users to the relevant sections of react-rxjs.org.
=> docs(monorepo): update README files

packages/core/src/internal/share-latest.ts, packages/core/src/operators/share-latest.test.ts
I'm opening this PR for the sake of sharing knowledge/transparency.
I found this pretty annoying bug with `shareLatest` that only happens in a pretty edge-case situation that can be seen in the test of the first commit of this PR.
=> fix(core/shareLatest): recursive sync subscriptions

packages/core/src/internal/share-latest.ts
I noticed this silly (and kinda superfluous) logic on `shareLatest`... It's a mistake that I made when I wrote the code for supporting error boundaries on suspense and I'm quite confident this is the correct code. It's difficult to come up with a breaking test, because AFAIK the previous code didn't trigger any issues.
=> chore(shareLatest): simplify implementation

packages/core/src/shareLatest.ts, packages/utils/src/collect.ts, packages/utils/src/collectValues.ts, packages/utils/src/split.ts, packages/utils/src/suspended.ts, packages/utils/src/switchMapSuspended.ts
- use OperatorFunction and MonoTypeOperatorFunction where appropriate
- switch order of type arguments on "split" (from K,T,R to T,K,R) so that it matches other operators like groupBy
- change typings of switchMapSuspended so that it matches RxJs switchMap (now uses ObservedValueOf)
no code changes; all tests still pass
=> chore(typings): bring types in line with RxJs

README.md
- remove references to graceTime from root readme, i.e. bring in line with packages readme
=> chore(docs): fix local readme

packages/core/src/Subscribe.tsx, packages/core/src/internal/useObservable.ts, packages/core/src/useLayoutEffect.ts, packages/core/src/useSubscribe.ts
This reverts commit 973669553b98befc4256a3979870de59b4d58950.
I was preparing a PR to `will-this-react-global-state-work-in-concurrent-mode` to update the name of the library and to use the latest version, and as I was doing that I realized that the test `ability to interrupt render` was not passing. It turns out that's because of the theoretical perf improvement of using `useLayoutEffect` rather than using `useEffect`. So, after having thought about this quite a bit, I'm quite positive that we should revert this commit.
=> Revert "perf(core): use useLayoutEffect"

packages/core/src/bind/connectFactoryObservable.test.tsx, packages/core/src/bind/connectFactoryObservable.ts
As @voliva pointed out to me offline, the current behaviour of the shared-observable returned from the "factory bind" is problematic, because a consumer could want to resubscribe to it after all its initial subscriptions have finished. Currently this would trigger an error and that's not the intended behaviour.
This PR addresses the behaviour of what it should occur when a new subscription happens on a shared-observable that was previously disposed. There are 2 possible scenarios here:
1) When the new subscription happens there is no instance on the cache for that given key: in this case a new instance will be added and all subsequent subscriptions will consume that instance until it's no longer needed.
2) There is already a new instance on the cache: in this case the new subscription …
=> fix(core): factory bind multiple (un/re)subscriptions

packages/utils/src/createListener.spec.ts, packages/utils/src/createListener.ts, packages/utils/src/index.tsx
Closes #126 
After an "offline" conversation with @rikoe he convinced me that `createListener` -despite being a bit verbose- it's a better name than `newInput` or than `createInput`, and I think that he is right. So, here we go. Are we all happy with the name and with the signature?
=> utils(createListener): add createListener util

packages/utils/src/internal-utils.ts, packages/utils/src/suspend.test.ts, packages/utils/src/suspend.ts, packages/utils/src/suspended.test.ts, packages/utils/src/switchMapSuspended.test.ts
BREAKING CHANGE: suspend, suspended and switchMapSuspended will only emit SUSPENSE if the source doesn't emit synchronously
=> feat(utils): startWith -> defaultStart on suspense utils

packages/core/src/bind/connectFactoryObservable.test.tsx, packages/core/src/bind/connectFactoryObservable.ts, packages/core/src/bind/connectObservable.test.tsx, packages/core/src/bind/connectObservable.ts, packages/core/src/internal/BehaviorObservable.ts, packages/core/src/internal/react-enhancer.ts, packages/core/src/internal/share-latest.ts, packages/core/src/internal/useObservable.ts, packages/dom/src/batchUpdates.test.tsx
The `graceTime` is a dangerous thing. No one should rely on it, it's an implementation detail. So, I've decided to remove it because it's not as useful as I initial thought it was. Also, it adds lots of unnecessary complexity.
There are 3 different commits in this PR:
1. Gets rid of the graceTimesecond
2. Simplifies *a lot* both: the `reactEnhancer` and `useObservable`
3. Removes `reactEnhancer` :tada:
=> Removing graceTime and adding lots of perf improvements

package.json, packages/core/package.json, packages/dom/package.json, packages/utils/package.json, yarn.lock
While I'm happy to see that all our tests are pass on React 17, I think that we should have a way to run our tests against different versions of react & rxjs... I wonder what the best way to go about that would be 🤔  @voliva any ideas?
=> chore(deps): upgrade dependencies

packages/core/src/Subscribe.test.tsx, packages/core/src/Subscribe.tsx, packages/core/src/bind/connectFactoryObservable.test.tsx, packages/core/src/bind/connectFactoryObservable.ts, packages/core/src/bind/connectObservable.test.tsx, packages/core/src/bind/connectObservable.ts, packages/core/src/internal/useObservable.ts
I had an issue caused because I was receiving the old value from a factory `bind(id => ...)` when switching its key based on a router's param.
We realised this shouldn't happen when using `Subscribe` boundaries properly, but Subscribe doesn't currently handle the case of the source stream switching.
In here I add two tests: The first one tries to represent the underlying issue in Subscribe, but it turned out really contrived. So I also added a second test which better represents the issue I was having initially.
=> fix(core/subscribe): stop rendering children when source$ switches

packages/core/src/bind/connectFactoryObservable.test.tsx, packages/core/src/bind/connectObservable.test.tsx
=> test(bind): supports observables of functions

packages/core/src/bind/connectFactoryObservable.test.tsx, packages/core/src/bind/connectFactoryObservable.ts, packages/core/src/bind/connectObservable.ts, packages/core/src/internal/useObservable.ts
Closes #156 
I'm not really sure we would officially support this feature, although it has been working on and off for a while. In our mental model, the parameters of a parametric `bind` are used to identify an instance of an entity.
As v0.5 is a version that helps the migration from 0.4 to 0.6 I think it's useful anyway to have this in.
=> fix(bind): supports variadic number of arguments

packages/core/package.json, packages/core/src/Subscribe.tsx, packages/core/src/bind/connectFactoryObservable.test.tsx, packages/core/src/bind/connectFactoryObservable.ts, packages/core/src/internal/share-latest.ts, packages/core/src/internal/useObservable.ts, packages/dom/package.json, packages/utils/package.json
A little bit of context of what this bug is and how it got introduced, since we may need to revisit this in the future:
The issue got introduced by [this "fix"](https://github.com/re-rxjs/react-rxjs/commit/20e95697bb8faff51bcf55c1abe054d1f7ff4656). Let's first understand what that "fix" was about: If the `Subscribe` component gets remounted and the only consumers of its `source$` are its `children`, then the desired behavior is that when it remounts the `source$` shouldn't have any subscribers. However, that's not what was happening. There was a race-condition in which when the mount logic of the `Subscribe` component was being executed, the cleanup function for the `Subscribe` component had been evaluated, but the cleanup function of its children  hadn't been evaluated.
In order to "fix" …
=> fix(core): ensure that all subscriptions count for the refcount

packages/core/src/bind/connectFactoryObservable.test.tsx, packages/core/src/bind/connectFactoryObservable.ts, packages/core/src/bind/index.ts
I've been meaning to make this improvement for a while now, but I never got to it... Technically speaking, this is a breaking change. Because in the super-rare event that someone was using a factory `bind` with Observables of functions and that the default-value overload was being used, then they will have to wrap that default function into another function... So, yeah, this should go into `0.7.0` I guess :shrug: 
@voliva  what do you think?
=> feat(core): factory `bind` accept function for default value

packages/core/src/internal/share-latest.ts, packages/core/src/share-latest.test.ts
Basically, bringing [this](https://github.com/ReactiveX/rxjs/pull/6370) to react-rxjs
=> fix(shareLatest): properly closing sync observables

packages/utils/src/combineKeys.test.ts, packages/utils/src/combineKeys.ts, packages/utils/src/index.tsx
Recently I found a use case where I'd like to have an operator similar to `combineKeys`, but that instead of emitting a map of values it would just emit the latest individual change.
I couldn't find any way of composing the existing operators to do this, so I had to make a custom operator which had mostly combineKeys' code changing a few lines.
After discussing it we found out that this operator would be easy to implement if the existing `combineKeys` also emitted the list of keys that have changed. This is a posible implementation.
With this operator, the mergeKeys operator I had in mind would become something like:
```ts
const mergeKeys = <K, T>(keys$: Observable<K>, getInner$: (key: K) => Observable<T>): Observable<T> =>
combineKeys(keys$, getInner$).pipe(
mergeMap(values => {
return …
```
=> feat(utils/combineKeys): emit set with changed keys

packages/core/src/internal/useObservable.ts
We're using `react-rxjs` but have transitioned away to an SSR framework, however Node doesn't seem to support this syntax of importing from a directory without specifically writing `index.js`. 
Installing `react-rxjs` on a freshly setup Next.js project yields the following error when trying to import `bind` from `@react-rxjs/core`:
```
Error: Directory import '*<project>*/node_modules/use-sync-external-store/shim' is not supported resolving ES modules imported from *<project>*/node_modules/@react-rxjs/core/dist/core.es2019.mjs
Did you mean to import use-sync-external-store/shim/index.js?
```
=> Fix compile error on Next.js 12 (Directory import)

packages/core/src/Subscribe.test.tsx, packages/core/src/Subscribe.tsx, packages/core/src/useStateObservable.ts
This PR adds a new test, which is currently failing on the `main` branch, and its corresponding fix.
=> fix: Subscribe with async errors

packages/core/src/Subscribe.test.tsx, packages/core/src/Subscribe.tsx
Unfortunately the test doesn't reproduce it :(
Maybe it's related to the testing framework? A simple sandbox does reproduce it: https://codesandbox.io/s/react-rxjs-playground-sfty1h?file=/src/App.tsx
I'll take a closer look this evening
=> fix Subscribe throwing NoSubscribersError on synchronous completes

package-lock.json, packages/core/package.json, packages/dom/package.json, packages/utils/package.json
Fixes #298
I've brought it to @rx-state/core as well, released for 0.1.3
Sorry it took long to fix this @bmcbarron, I've tried it in local and it looks like this should work, right?
=> fix: types not read when moduleResolution is not "node"

package-lock.json, package.json, packages/core/src/Subscribe.test.tsx, packages/core/src/Subscribe.tsx, packages/core/src/bind/connectObservable.test.tsx, packages/core/src/test-helpers/pipeableStreamToObservable.ts, packages/core/src/useStateObservable.ts
Fixes #305 
Something important to keep in mind is that in SSR any children within a `Subscribe` will not render, because given that components never mount in SSR (including `<Subscribe>`), it will never get into the stage of rendering the children.
And `StateObservable` with top-level subscriptions will have their state shared between clients.
=> Add getServerSnapshot, fix loop on SSR Subscribe
