README.md
I'm not sure about this, but I'm thinking about adding a kinda complete example on the README until the first version of the docs is ready... What do you think @voliva ?
=> Docs: add new example to the README

package-lock.json, package.json
=> chore: bundlesize

test/connectFactoryObservable.test.tsx
These covers the 3 remaining points identified for connectFactoryObservable in #20
=> test: connectFactoryObservable updates, subscriptions and errors.

test/connectObservable.test.tsx
I'm creating a PR just to demonstrate a way to test "re-renders" with `@testing-library/react-hooks`.
cc @voliva @bhavesh-desai-scratch
=> Improve connectObservable tests

src/internal/share-latest.ts
@voliva FYI
I'm mergning this, because I'm quite confident that it can not break anything. Also all the tests are passing. That being said, @voliva please have a look at this whenever you can. Thanks!
=> refactor(shareLatest): Improve shareLatest implementation

README.md
Found a couple syntax errors in TSX examples. I also replaced two instances of `<div />`s being used instead of `<p />`. Happy to revert that change if you prefer `<div />`.
=> Fix a few typos and invalid code in README.md

.travis.yml, package.json, packages/core/package.json, packages/dom/package.json, packages/utils/package.json, yarn.lock
An attempt to fix the CI issues
=> chore(ci): fix CI

packages/core/src/internal/react-enhancer.ts, packages/core/src/internal/share-latest.ts
Size matters! :joy: (my guess is that this should decrease the bundle-size a tiny-tiny bit :joy:)
=> chore: refactor avoid object subscriptions

.github/workflows/CI.yml, package.json, packages/core/package.json, packages/dom/package.json, packages/utils/package.json, yarn.lock
I noticed that after #84 neither codecov nor bundlewatch were working properly, this is an attempt to port the same functionality to GH actions :crossed_fingers:
=> chore(ci): Improve GH actions

packages/utils/src/collect.ts, packages/utils/src/collectValues.ts, packages/utils/src/internal-utils.ts
Is this a "hasty" abstraction? Maybe, but it does reduce the bundle size 🙈
=> chore(utils): collector abstraction to reduce bundle size

packages/core/package.json, packages/dom/package.json, packages/utils/package.json
I started this thing, yep... but I really think of @voliva as a co-author of this library. His insights, his feedback, his proposals, all the contributions that his made to the API, etc, etc. I don't think that it's fair that my name is the only one on the list of authors.
So, @voliva can I add you to the list of "authors"?
=> chore: Add Victor as a co-author

packages/core/src/bind/connectFactoryObservable.test.tsx, packages/core/src/bind/connectFactoryObservable.ts, packages/core/src/bind/connectObservable.ts, packages/core/src/internal/COMPLETE.ts, packages/core/src/internal/react-enhancer.ts, packages/core/src/internal/share-latest.ts, packages/core/src/internal/take-until-complete.ts, packages/core/src/shareLatest.ts
=> fix(core-bind): shared observable should not complete

packages/utils/src/split.test.ts, packages/utils/src/split.ts
=> fix(utils-split): dismiss inner observable on error

packages/core/package.json, packages/dom/package.json, packages/utils/package.json
=> core v0.4.2

yarn.lock
Re-installing tsdx in order to get rid of a security warning that [does not affect us](https://github.com/formium/tsdx/pull/731#issuecomment-679181191).
=> chore(deps): re-install tsdx

packages/dom/src/batchUpdates.test.tsx
Once in a blue moon we get a random broken CI build and when I check what's broken I find that the test "batchUpdates prevents unnecessary updates" has received 9 updates rather than 6, when that happens I re-run the CI and then the test passes. I've been thinking about it and I think that I know what's causing that and I think that this changes should stop the flakiness of the test.
Basically, what I think that happens is that in some cases the initial mount takes longer than 250ms and then the subscription happens again, causing an extra-update. Using `Subscribe` should fix that.
=> test(dom): fix flaky test

packages/core/src/internal/react-enhancer.ts
There are a few good reasons for this change:
- Better performance
- Total bundle-size (in case that the consumer is not using these 3 operators)
- if one day the `Observable` proposal makes it through, then `@core` won't even need `rxjs` as a peer-dependency 🤯 . Let me dream, ok? 😅
=> chore(core): avoid using rxjs/operators

packages/core/src/bind/connectFactoryObservable.test.tsx, packages/core/src/bind/connectFactoryObservable.ts, packages/core/src/bind/connectObservable.test.tsx, packages/core/src/bind/connectObservable.ts, packages/core/src/bind/index.ts, packages/core/src/internal/react-enhancer.ts, packages/core/src/internal/useObservable.ts
I can't wait to get this in!! 😬
=> feat(core): default value on bind

packages/core/src/bind/connectFactoryObservable.test.tsx, packages/core/src/bind/connectObservable.test.tsx, packages/core/src/internal/useObservable.ts
=> fix(bind): supports observables of functions (0.5)

package.json, packages/core/package.json, packages/dom/package.json, packages/utils/package.json
Based on [this](https://web.dev/publish-modern-javascript/#modern-with-legacy-fallback-and-esm-bundler-optimizations).
=> chore: improve bundling

packages/dom/package.json, packages/utils/package.json
=> chore: fix devDependencies

.gitignore, packages/core/dist/index.js, packages/core/package.json, packages/dom/dist/index.js, packages/dom/package.json, packages/utils/dist/index.js, packages/utils/package.json
=> chore: patch exports for all packages

packages/utils/src/partitionByKey.test.ts, packages/utils/src/partitionByKey.ts
=> fix(utils): partitionByKey make streamSelector optional

packages/core/package.json, packages/dom/package.json, packages/utils/package.json
=> fix: package.json exports

packages/core/package.json
=> @react-rxjs/core@0.8.6 fix build

README.md
=> docs: update bundlephobia link

package-lock.json, packages/core/cjsBuild.js, packages/core/jest.config.js, packages/core/package.json, packages/core/src/SUSPENSE.ts, packages/core/src/Subscribe.test.tsx, packages/core/src/Subscribe.tsx, packages/core/src/bind/connectFactoryObservable.test.tsx, packages/core/src/bind/connectFactoryObservable.ts, packages/core/src/bind/connectObservable.test.tsx, packages/core/src/bind/connectObservable.ts, packages/core/src/bind/index.ts, packages/core/src/index.tsx, packages/core/src/stateJsx.test.tsx, packages/core/src/stateJsx.tsx, packages/core/src/useStateObservable.ts, packages/dom/package.json, packages/utils/package.json
Main features:
* Support `sinkSuspense` and `liftSuspense`
* Use StateObservables as React elements
=> Release 0.10

packages/utils/src/index.tsx, packages/utils/src/selfDependent.test.ts, packages/utils/src/selfDependent.ts
=> chore: rename selfDependant to selfDependent
